trigger: none

pr:
- dev

pool:
  vmImage: 'ubuntu-20.04'

variables:
  buildContext: 'FHICORC.Backend'
  apiImageName: 'fhicorc-verification-backend'
  hangfireImageName: 'fhicorc-verification-hangfire'
  dbMigrationsImageName: 'fhicorc-verification-dbmigrations'

steps:
- task: Docker@2
  displayName: Build and Push API docker image
  inputs:
    containerRegistry: 'FHI-Koronasertifikat.Verifisering-ACR-QA'
    repository: '$(apiImageName)'
    command: 'buildAndPush'
    Dockerfile: '$(buildContext)/FHICORC.ApplicationHost.Api/Dockerfile'
    buildContext: '$(buildContext)'

- task: Docker@2
  displayName: Build and Push Hangfire docker image
  inputs:
    containerRegistry: 'FHI-Koronasertifikat.Verifisering-ACR-QA'
    repository: '$(hangfireImageName)'
    command: 'buildAndPush'
    Dockerfile: '$(buildContext)/FHICORC.ApplicationHost.Hangfire/Dockerfile'
    buildContext: '$(buildContext)'

- task: Docker@2
  displayName: Build and Push DbMigrations docker image
  inputs:
    containerRegistry: 'FHI-Koronasertifikat.Verifisering-ACR-QA'
    repository: '$(dbMigrationsImageName)'
    command: 'buildAndPush'
    Dockerfile: '$(buildContext)/FHICORC.ApplicationHost.DbMigrations/Dockerfile'
    buildContext: '$(buildContext)'
