trigger: none

pr: none

pool:
  vmImage: 'ubuntu-20.04'
  
variables:
- template: ../version-number.yml
- name: versionRev
  value: $[counter(variables['version'], 1)]
- name: finalVersion
  value: $(version)-rev.$(versionRev)
- name: azureConnection
  value: FHI-Koronasertifikat.Verifisering-ARM-Test

extends:
  template: cd-build-push-image-pipeline.yml
  parameters:
    containerRegistry: FHI-Koronasertifikat.Verifisering-ACR-Test
    azureConnection: ${{ variables.azureConnection }}
    appVersion: $(finalVersion)
    doRelease: 'true'
    environment: 'test'
