trigger: none

pr: none

pool:
  vmImage: 'ubuntu-20.04'

variables:
- template: ../version-number.yml
  
extends:
  template: cd-build-push-image-pipeline.yml
  parameters:
    containerRegistry: FHI-Koronasertifikat.Verifisering-ACR-Prod
    appVersion: $(version)
    doRelease: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
    environment: 'prod'
