trigger: none

pr: none

pool:
  vmImage: 'ubuntu-20.04'
  
variables:
  version: 2.1.0
  versionRev: $[counter(variables['version'], 1)]
  finalVersion: $(version)-rev.$(versionRev)
  
extends:
  template: cd-build-push-image-pipeline.yml
  parameters:
    containerRegistry: FHI-Koronasertifikat.Verifisering-ACR-Test
    appVersion: $(finalVersion)
    doRelease: 'true'
    environment: 'test'
