trigger: none

pr: none

pool:
  vmImage: 'ubuntu-20.04'
   
variables:
- template: ../version-number.yml
- name: versionRev
  value: $[counter(variables['version'], 1)]
- name: finalVersion
  value: $(version)-rc.$(versionRev)

extends:
  template: cd-build-push-image-pipeline.yml
  parameters:
    containerRegistry: FHI-Koronasertifikat.Verifisering-ACR-QA
    appVersion: $(finalVersion)
    doRelease: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/release/') }}
    environment: 'preprod'
