// <auto-generated />
using System;
using FHICORC.Infrastructure.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FHICORC.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CoronapassContext))]
    partial class CoronapassContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("FHICORC.Domain.Models.BatchesRevoc", b =>
                {
                    b.Property<string>("BatchId")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HashType")
                        .HasColumnType("text");

                    b.Property<string>("Kid")
                        .HasColumnType("text");

                    b.Property<int?>("SuperId")
                        .HasColumnType("integer");

                    b.Property<bool>("Upload")
                        .HasColumnType("boolean");

                    b.HasKey("BatchId");

                    b.HasIndex("SuperId");

                    b.ToTable("BatchesRevoc");
                });

            modelBuilder.Entity("FHICORC.Domain.Models.BusinessRule", b =>
                {
                    b.Property<int>("BusinessRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("RuleIdentifier")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RuleJson")
                        .HasColumnType("varchar(20000)");

                    b.HasKey("BusinessRuleId");

                    b.HasIndex("RuleIdentifier")
                        .IsUnique();

                    b.ToTable("BusinessRules");
                });

            modelBuilder.Entity("FHICORC.Domain.Models.CountriesReportModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CountriesReport")
                        .HasColumnType("varchar(5000)");

                    b.HasKey("Id");

                    b.ToTable("CountriesReportModels");
                });

            modelBuilder.Entity("FHICORC.Domain.Models.EuDocSignerCertificate", b =>
                {
                    b.Property<int>("EuDocSignerCertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Certificate")
                        .HasColumnType("text");

                    b.Property<string>("CertificateType")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("KeyIdentifier")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PublicKey")
                        .HasColumnType("text");

                    b.Property<string>("Signature")
                        .HasColumnType("text");

                    b.Property<string>("Thumbprint")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("EuDocSignerCertificateId");

                    b.ToTable("EuDocSignerCertificates");
                });

            modelBuilder.Entity("FHICORC.Domain.Models.FiltersRevoc", b =>
                {
                    b.Property<string>("BatchId")
                        .HasColumnType("text");

                    b.Property<string>("BatchesRevocBatchId")
                        .HasColumnType("text");

                    b.Property<byte[]>("Filter")
                        .HasMaxLength(5992)
                        .HasColumnType("bytea");

                    b.HasKey("BatchId");

                    b.HasIndex("BatchesRevocBatchId");

                    b.ToTable("FiltersRevoc");
                });

            modelBuilder.Entity("FHICORC.Domain.Models.HashesRevoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BatchId")
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("HashesRevoc");
                });

            modelBuilder.Entity("FHICORC.Domain.Models.SuperFiltersRevoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BatchCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("SuperExpires")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("SuperFilter")
                        .HasMaxLength(5992)
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("SuperFiltersRevoc");
                });

            modelBuilder.Entity("FHICORC.Domain.Models.BatchesRevoc", b =>
                {
                    b.HasOne("FHICORC.Domain.Models.SuperFiltersRevoc", "SuperFiltersRevoc")
                        .WithMany("BatchesRevocs")
                        .HasForeignKey("SuperId");

                    b.Navigation("SuperFiltersRevoc");
                });

            modelBuilder.Entity("FHICORC.Domain.Models.FiltersRevoc", b =>
                {
                    b.HasOne("FHICORC.Domain.Models.BatchesRevoc", "BatchesRevoc")
                        .WithMany("FiltersRevocs")
                        .HasForeignKey("BatchesRevocBatchId");

                    b.Navigation("BatchesRevoc");
                });

            modelBuilder.Entity("FHICORC.Domain.Models.HashesRevoc", b =>
                {
                    b.HasOne("FHICORC.Domain.Models.BatchesRevoc", "BatchesRevoc")
                        .WithMany("HashesRevocs")
                        .HasForeignKey("BatchId");

                    b.Navigation("BatchesRevoc");
                });

            modelBuilder.Entity("FHICORC.Domain.Models.BatchesRevoc", b =>
                {
                    b.Navigation("FiltersRevocs");

                    b.Navigation("HashesRevocs");
                });

            modelBuilder.Entity("FHICORC.Domain.Models.SuperFiltersRevoc", b =>
                {
                    b.Navigation("BatchesRevocs");
                });
#pragma warning restore 612, 618
        }
    }
}
