trigger: none

pr: none

pool:
  vmImage: 'ubuntu-20.04'

variables: 
- template: ../version-number.yml
- name: finalVersion
  value: $(version)-data
  
extends:
  template: cd-push-rules-pipeline.yml
  parameters:
    containerRegistry: FHI-Koronasertifikat.Verifisering-ACR-Prod
    appVersion: $(finalVersion)
    doRelease: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
    environment: 'prod'
