trigger: none

pr: none

pool:
  vmImage: 'ubuntu-20.04'
  
variables: 
- template: ../version-number.yml
- name: versionRev
  value: $[counter(variables['version'], 1)]
- name: finalVersion
  value: $(version)-data-rev.$(versionRev)
  
extends:
  template: cd-push-rules-pipeline.yml
  parameters:
    containerRegistry: FHI-Koronasertifikat.Verifisering-ACR-Test
    appVersion: $(finalVersion)
    doRelease: 'true'
    environment: 'test'
