trigger: none

pr: none

pool:
  vmImage: 'ubuntu-20.04'
  
variables:
  version: 2.2.0
  versionRev: $[counter(variables['version'], 1)]
  finalVersion: $(version)-data-rc.$(versionRev)

extends:
  template: cd-push-rules-pipeline.yml
  parameters:
    containerRegistry: FHI-Koronasertifikat.Verifisering-ACR-QA
    appVersion: $(finalVersion)
    doRelease: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/release/') }}
    environment: 'preprod'
